# For use with VS Code REST Client extension

GET http://localhost:8080/list

###

POST http://localhost:8080/list
content-type: application/json

Apple

###
DELETE http://localhost:8080/list/1
content-type: application/json

###

PUT http://localhost:8080/list?itemId=2&updatedItem=NewApple
content-type: application/json